exports.seed = function(knex, Promise) {
  return knex.raw('DELETE FROM "player_game"; ALTER SEQUENCE player_game_id_seq RESTART WITH 23;')
    .then(() => {
      let gameStats = [{
        id: 1,
        player_id: 1,
        game_id: 1,
        at_bat: 4,
        single: 2,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 1
      }, {
        id: 2,
        player_id: 2,
        game_id: 1,
        at_bat: 4,
        single: 1,
        double: 1,
        triple: 0,
        homerun: 1,
        walk: 0,
        rbi: 3
      }, {
        id: 3,
        player_id: 3,
        game_id: 1,
        at_bat: 4,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 4,
        player_id: 4,
        game_id: 1,
        at_bat: 4,
        single: 2,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 1
      }, {
        id: 5,
        player_id: 5,
        game_id: 1,
        at_bat: 4,
        single: 1,
        double: 0,
        triple: 1,
        homerun: 0,
        walk: 0,
        rbi: 2
      }, {
        id: 6,
        player_id: 6,
        game_id: 1,
        at_bat: 4,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 7,
        player_id: 7,
        game_id: 1,
        at_bat: 4,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 1,
        rbi: 1
      }, {
        id: 8,
        player_id: 8,
        game_id: 1,
        at_bat: 3,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 1,
        rbi: 0
      }, {
        id: 9,
        player_id: 9,
        game_id: 1,
        at_bat: 3,
        single: 3,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 1
      }, {
        id: 10,
        player_id: 10,
        game_id: 1,
        at_bat: 3,
        single: 0,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 11,
        player_id: 11,
        game_id: 1,
        at_bat: 3,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 12,
        player_id: 1,
        game_id: 2,
        at_bat: 5,
        single: 2,
        double: 1,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 2
      }, {
        id: 13,
        player_id: 2,
        game_id: 2,
        at_bat: 5,
        single: 2,
        double: 0,
        triple: 0,
        homerun: 1,
        walk: 0,
        rbi: 4
      }, {
        id: 14,
        player_id: 3,
        game_id: 2,
        at_bat: 5,
        single: 1,
        double: 2,
        triple: 1,
        homerun: 0,
        walk: 0,
        rbi: 2
      }, {
        id: 15,
        player_id: 4,
        game_id: 2,
        at_bat: 5,
        single: 2,
        double: 0,
        triple: 1,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 16,
        player_id: 5,
        game_id: 2,
        at_bat: 5,
        single: 0,
        double: 2,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 1
      }, {
        id: 17,
        player_id: 6,
        game_id: 2,
        at_bat: 4,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 18,
        player_id: 7,
        game_id: 2,
        at_bat: 4,
        single: 0,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 19,
        player_id: 8,
        game_id: 2,
        at_bat: 4,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 0
      }, {
        id: 20,
        player_id: 9,
        game_id: 2,
        at_bat: 4,
        single: 1,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 1,
        rbi: 0
      }, {
        id: 21,
        player_id: 10,
        game_id: 2,
        at_bat: 4,
        single: 0,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 1,
        rbi: 0
      }, {
        id: 22,
        player_id: 11,
        game_id: 2,
        at_bat: 4,
        single: 2,
        double: 0,
        triple: 0,
        homerun: 0,
        walk: 0,
        rbi: 1
      }]
      return knex('player_game').insert(gameStats)
    })
};
